

"use strict";

/**
 * Card deck.
 */
Game.deck = [
	{"id": 1, "name": "Pickaxe", "ranks": [1,5,4,1], "element": "EARTH", "level": 1},
	{"id": 2, "name": "Iota shrimp", "ranks": [5,3,1,1], "element": "WATER", "level": 1},
	{"id": 3, "name": "Snoo", "ranks": [1,4,3,3], "element": "NEUTRAL", "level": 1},
	{"id": 4, "name": "Old miner", "ranks": [4,2,1,1], "element": "EARTH", "level": 1},
	{"id": 5, "name": "Huge dump", "ranks": [2,5,3,1], "element": "POISON", "level": 1},
	{"id": 6, "name": "1 Iota", "ranks": [2,4,1,4], "element": "WIND", "level": 1},
	{"id": 7, "name": "Load of shitcoin", "ranks": [1,1,5,4], "element": "NEUTRAL", "level": 1},
	{"id": 8, "name": "Strong dyslexia", "ranks": [2,3,5,2], "element": "NEUTRAL", "level": 1},
	{"id": 9, "name": "Iota crab", "ranks": [2,1,1,6], "element": "WATER", "level": 1},
	{"id": 10, "name": "Strong miner", "ranks": [4,3,2,4], "element": "EARTH", "level": 1},
	{"id": 11, "name": "Iota light wallet", "ranks": [2,6,1,2], "element": "WIND", "level": 1},
	{"id": 12, "name": "Trezor wallet", "ranks": [7,1,1,3], "element": "NEUTRAL", "level": 2},
	{"id": 13, "name": "Ledger nano blue", "ranks": [6,3,2,2], "element": "NEUTRAL", "level": 2},
	{"id": 14, "name": "Binance", "ranks": [5,4,3,3], "element": "HOLY", "level": 2},
	{"id": 15, "name": "Raspberry pi", "ranks": [6,3,1,4], "element": "NEUTRAL", "level": 2},
	{"id": 16, "name": "Bitconneeeeeect", "ranks": [3,3,4,5], "element": "POISON", "level": 2},
	{"id": 17, "name": "Suspicious doggo", "ranks": [5,5,3,2], "element": "NEUTRAL", "level": 2},
	{"id": 18, "name": "Iota octopus", "ranks": [5,5,1,3], "element": "WATER", "level": 2},
	{"id": 19, "name": "Pump and dump", "ranks": [5,2,4,1], "element": "NEUTRAL", "level": 2},
	{"id": 20, "name": "Iota fish", "ranks": [4,2,4,5], "element": "WATER", "level": 2},
	{"id": 21, "name": "Old wife not believing in me", "ranks": [3,7,2,1], "element": "POISON", "level": 2},
	{"id": 22, "name": "Very expensive pizza", "ranks": [5,3,2,5], "element": "NEUTRAL", "level": 2},
	{"id": 23, "name": "r/CyproCurrency mod", "ranks": [6,2,6,3], "element": "HOLY", "level": 3},
	{"id": 24, "name": "1 Miota", "ranks": [6,6,3,1], "element": "WIND", "level": 3},
	{"id": 25, "name": "Old mine", "ranks": [3,5,5,5], "element": "EARTH", "level": 3},
	{"id": 26, "name": "Iota dolphin", "ranks": [7,3,5,1], "element": "WATER", "level": 3},
	{"id": 27, "name": "Ledger nano S", "ranks": [7,3,1,5], "element": "NEUTRAL", "level": 3},
	{"id": 28, "name": "Tangle explorer", "ranks": [1,3,2,3], "element": "WIND", "level": 3},
	{"id": 29, "name": "Omuku", "ranks": [5,4,6,2], "element": "HOLY", "level": 3},
	{"id": 30, "name": "Gdax / Coinbase Pro", "ranks": [4,2,4,7], "element": "HOLY", "level": 3},
	{"id": 31, "name": "Anti-whale gun", "ranks": [6,3,2,6], "element": "NEUTRAL", "level": 3},
	{"id": 32, "name": "Crazy cryptobot", "ranks": [3,4,6,4], "element": "THUNDER", "level": 3},
	{"id": 33, "name": "Bear", "ranks": [7,5,2,3], "element": "ICE", "level": 3},
	{"id": 34, "name": "Jinn", "ranks": [2,7,3,6], "element": "NEUTRAL", "level": 4},
	{"id": 35, "name": "Weird cryptoguy", "ranks": [6,5,5,4], "element": "POISON", "level": 4},
	{"id": 36, "name": "Huge electricity bill", "ranks": [4,7,6,2], "element": "THUNDER", "level": 4},
	{"id": 37, "name": "A nice bubble", "ranks": [4,3,5,6], "element": "FIRE", "level": 4},
	{"id": 38, "name": "Iota seed", "ranks": [1,7,6,4], "element": "WIND", "level": 4},
	{"id": 39, "name": "Carlos Matos", "ranks": [7,6,3,1], "element": "POISON", "level": 4},
	{"id": 40, "name": "A nice pyramid", "ranks": [7,4,4,4], "element": "NEUTRAL", "level": 4},
	{"id": 41, "name": "Tangle monitor", "ranks": [3,6,7,3], "element": "WIND", "level": 4},
	{"id": 42, "name": "Crypto winter", "ranks": [6,3,2,7], "element": "ICE", "level": 4},
	{"id": 43, "name": "Iota shark", "ranks": [4,6,5,5], "element": "WATER", "level": 4},
	{"id": 44, "name": "Nice pump", "ranks": [5,3,5,4], "element": "NEUTRAL", "level": 4},
	{"id": 45, "name": "Hacker", "ranks": [6,5,5,6], "element": "THUNDER", "level": 5},
	{"id": 46, "name": "Bull", "ranks": [3,4,9,4], "element": "NEUTRAL", "level": 5},
	{"id": 47, "name": "The coordinator", "ranks": [7,3,6,5], "element": "WATER", "level": 5},
	{"id": 48, "name": "Github", "ranks": [3,1,10,2], "element": "NEUTRAL", "level": 5},
	{"id": 49, "name": "A farm in Iceland", "ranks": [4,1,2,6], "element": "FIRE", "level": 5},
	{"id": 50, "name": "Exit scam", "ranks": [5,4,5,7], "element": "POISON", "level": 5},
	{"id": 51, "name": "Trinity wallet", "ranks": [7,2,7,4], "element": "WIND", "level": 5},
	{"id": 52, "name": "Tiny virus", "ranks": [7,4,2,7], "element": "THUNDER", "level": 5},
	{"id": 53, "name": "Cryptowhale", "ranks": [5,6,3,7], "element": "WATER", "level": 5},
	{"id": 54, "name": "1 Giota", "ranks": [4,4,6,7], "element": "WIND", "level": 5},
	{"id": 55, "name": "Iota whale", "ranks": [6,7,6,2], "element": "WATER", "level": 5},
	{"id": 56, "name": "1 Bitcoin", "ranks": [2,4,8,8], "element": "FIRE", "level": 6},
	{"id": 57, "name": "The moon", "ranks": [7,4,8,3], "element": "NEUTRAL", "level": 6},
	{"id": 58, "name": "Qubic lite", "ranks": [4,3,8,7], "element": "WIND", "level": 6},
	{"id": 59, "name": "Iota white paper", "ranks": [7,5,2,8], "element": "WIND", "level": 6},
	{"id": 60, "name": "Unlimited power!", "ranks": [1,3,8,8], "element": "THUNDER", "level": 6},
	{"id": 61, "name": "Random Grandpa", "ranks": [8,2,2,8], "element": "NEUTRAL", "level": 6},
	{"id": 62, "name": "Taxe season", "ranks": [6,5,8,4], "element": "POISON", "level": 6},
	{"id": 63, "name": "Successful Ico", "ranks": [4,6,8,5], "element": "NEUTRAL", "level": 6},
	{"id": 64, "name": "Market cap", "ranks": [1,8,8,4], "element": "NEUTRAL", "level": 6},
	{"id": 65, "name": "Weird chain", "ranks": [6,4,5,8], "element": "THUNDER", "level": 6},
	{"id": 66, "name": "Iota research council", "ranks": [7,1,5,8], "element": "WIND", "level": 6},
	{"id": 67, "name": "Two", "ranks": [8,8,4,4], "element": "NEUTRAL", "level": 7},
	{"id": 68, "name": "Lambo", "ranks": [8,4,8,4], "element": "NEUTRAL", "level": 7},
	{"id": 69, "name": "CFB - True form", "ranks": [8,8,5,2], "element": "NEUTRAL", "level": 7},
	{"id": 70, "name": "IOTA logo", "ranks": [5,8,6,6], "element": "WIND", "level": 7},
	{"id": 71, "name": "No transaction fees", "ranks": [8,3,6,7], "element": "NEUTRAL", "level": 7},
	{"id": 72, "name": "Infinite scalability", "ranks": [8,8,3,5], "element": "NEUTRAL", "level": 7},
	{"id": 73, "name": "Resignation", "ranks": [8,4,8,5], "element": "NEUTRAL", "level": 7},
	{"id": 74, "name": "IOTA Ecosystem", "ranks": [5,5,7,8], "element": "WIND", "level": 7},
	{"id": 75, "name": "Car vertical", "ranks": [6,7,8,4], "element": "NEUTRAL", "level": 7},
	{"id": 76, "name": "Market crash", "ranks": [1,7,8,7], "element": "NEUTRAL", "level": 7},
	{"id": 77, "name": "Bitcoin ATM", "ranks": [7,8,7,2], "element": "FIRE", "level": 7},
	{"id": 78, "name": "Keepass", "ranks": [3,2,4,5], "element": "NEUTRAL", "level": 3},
	{"id": 79, "name": "Downtrend end", "ranks": [4,3,2,7], "element": "NEUTRAL", "level": 4},
	{"id": 80, "name": "Strong volatility", "ranks": [3,6,2,5], "element": "FIRE", "level": 4},
	{"id": 81, "name": "Eccentric cryptoguy", "ranks": [9,2,3,9], "element": "POISON", "level": 8},
	{"id": 82, "name": "Cryptowallet", "ranks": [2,4,4,5], "element": "NEUTRAL", "level": 4},
	{"id": 83, "name": "Coinbase", "ranks": [2,4,9,9], "element": "THUNDER", "level": 8},
	{"id": 84, "name": "The Tangle", "ranks": [6,9,7,4], "element": "WIND", "level": 8},
	{"id": 85, "name": "Paper wallet", "ranks": [2,3,1,2], "element": "ICE", "level": 2},
	{"id": 86, "name": "Coinye", "ranks": [1,2,3,4], "element": "NEUTRAL", "level": 1},
	{"id": 87, "name": "IamPass", "ranks": [5,9,1,9], "element": "THUNDER", "level": 8},
	{"id": 88, "name": "Iota fundation", "ranks": [9,9,5,2], "element": "WIND", "level": 8},
	{"id": 89, "name": "Talented designer", "ranks": [8,4,4,10], "element": "NEUTRAL", "level": 9},
	{"id": 90, "name": "Proof ow work", "ranks": [5,3,5,8], "element": "THUNDER", "level": 6},
	{"id": 91, "name": "Jerrycan of gas", "ranks": [2,5,2,5], "element": "NEUTRAL", "level": 3},
	{"id": 92, "name": "Direct acyclic graph", "ranks": [5,6,3,7], "element": "NEUTRAL", "level": 6},
	{"id": 93, "name": "Gas station", "ranks": [5,7,2,7], "element": "NEUTRAL", "level": 5},
	{"id": 94, "name": "Forgotten private key", "ranks": [7,4,5,6], "element": "NEUTRAL", "level": 5},
	{"id": 95, "name": "Legendary beard", "ranks": [3,2,5,8], "element": "HOLY", "level": 5},
	{"id": 96, "name": "Evil CEO", "ranks": [7,10,2,7], "element": "POISON", "level": 9},
	{"id": 97, "name": "Iota lochness", "ranks": [10,6,8,2], "element": "WATER", "level": 9},
	{"id": 98, "name": "Microhash", "ranks": [3,10,1,10], "element": "NEUTRAL", "level": 9},
	{"id": 99, "name": "1 Tiota", "ranks": [4,10,4,9], "element": "WIND", "level": 9},
	{"id": 100, "name": "CFB Human form", "ranks": [10,8,7,2], "element": "NEUTRAL", "level": 10},
	{"id": 101, "name": "SEC", "ranks": [6,10,7,6], "element": "NEUTRAL", "level": 10},
	{"id": 102, "name": "Satoshi Nakamoto", "ranks": [5,9,10,3], "element": "FIRE", "level": 10},
	{"id": 103, "name": "Market crash", "ranks": [10,4,8,6], "element": "NEUTRAL", "level": 10},
	{"id": 104, "name": "Julie Maupin", "ranks": [9,2,6,10], "element": "NEUTRAL", "level": 10},
	{"id": 105, "name": "Dr Rolf Werner", "ranks": [2,10,6,9], "element": "NEUTRAL", "level": 10},
	{"id": 106, "name": "Roman Semko", "ranks": [8,6,5,10], "element": "NEUTRAL", "level": 10},
	{"id": 107, "name": "Ralf Rottmann", "ranks": [4,10,10,2], "element": "NEUTRAL", "level": 10},
	{"id": 108, "name": "David Sønstebø", "ranks": [10,3,10,3], "element": "NEUTRAL", "level": 10},
	{"id": 109, "name": "Dominik Schiener", "ranks": [6,4,9,10], "element": "NEUTRAL", "level": 10},
	{"id": 110, "name": "Serguei Popov", "ranks": [10,9,4,6], "element": "NEUTRAL", "level": 10}
];